name: flutter_appcenter_bundle_updated_to_null_safety
description: This plugin currently bundles AppCenter Analytics, Crashes and Distribute. To learn more about AppCenter, go to https://aka.ms/appcenterdocs
version: 1.0.6
homepage: https://github.com/IngSm/flutter_appcenter_bundle_updated_to_null_safety

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: flutter_appcenter_bundle_updated_to_null_safety
        pluginClass: FlutterAppcenterBundlePlugin
      ios:
        pluginClass: FlutterAppcenterBundleUpdatedToNullSafetyPlugin
